/* ==========================================================================
   Schedula — quote library
   Format: [quote, author, source]   (source may be "")
   One quote is drawn per day with no repeats until every quote has been
   shown; then the deck reshuffles into a new cycle — it never runs out.
   Add your own anywhere in the list. Popular quotes that are commonly
   misattributed have been deliberately left out.
   ========================================================================== */
window.SCHEDULA_QUOTES = [
  // --- Stoics ---
  ["Waste no more time arguing about what a good man should be. Be one.", "Marcus Aurelius", "Meditations"],
  ["The impediment to action advances action. What stands in the way becomes the way.", "Marcus Aurelius", "Meditations"],
  ["The soul becomes dyed with the colour of its thoughts.", "Marcus Aurelius", "Meditations"],
  ["Confine yourself to the present.", "Marcus Aurelius", "Meditations"],
  ["Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", "Marcus Aurelius", "Meditations"],
  ["If it is not right, do not do it; if it is not true, do not say it.", "Marcus Aurelius", "Meditations"],
  ["Do every act of your life as though it were the very last act of your life.", "Marcus Aurelius", "Meditations"],
  ["Loss is nothing else but change, and change is Nature's delight.", "Marcus Aurelius", "Meditations"],
  ["The best revenge is to be unlike him who performed the injury.", "Marcus Aurelius", "Meditations"],
  ["How much more grievous are the consequences of anger than the causes of it.", "Marcus Aurelius", "Meditations"],
  ["Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.", "Marcus Aurelius", "Meditations"],
  ["Our life is what our thoughts make it.", "Marcus Aurelius", "Meditations"],
  ["Dig within. Within is the wellspring of good; and it is always ready to bubble up, if you just dig.", "Marcus Aurelius", "Meditations"],
  ["Never esteem anything as of advantage to you that will make you break your word or lose your self-respect.", "Marcus Aurelius", "Meditations"],
  ["It is not that we have a short time to live, but that we waste a lot of it.", "Seneca", "On the Shortness of Life"],
  ["The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today.", "Seneca", "On the Shortness of Life"],
  ["We suffer more often in imagination than in reality.", "Seneca", "Letters to Lucilius"],
  ["Begin at once to live, and count each separate day as a separate life.", "Seneca", "Letters to Lucilius"],
  ["While we are postponing, life speeds by.", "Seneca", "Letters to Lucilius"],
  ["Difficulties strengthen the mind, as labour does the body.", "Seneca", "Letters to Lucilius"],
  ["As is a tale, so is life: not how long it is, but how good it is, is what matters.", "Seneca", "Letters to Lucilius"],
  ["No man was ever wise by chance.", "Seneca", "Letters to Lucilius"],
  ["If a man knows not to which port he sails, no wind is favourable.", "Seneca", "Letters to Lucilius"],
  ["It is a rough road that leads to the heights of greatness.", "Seneca", "Letters to Lucilius"],
  ["Most powerful is he who has himself in his own power.", "Seneca", "Letters to Lucilius"],
  ["Associate with people who are likely to improve you.", "Seneca", "Letters to Lucilius"],
  ["He who is brave is free.", "Seneca", ""],
  ["Wherever there is a human being, there is an opportunity for a kindness.", "Seneca", ""],
  ["No man is free who is not master of himself.", "Epictetus", "Discourses"],
  ["First say to yourself what you would be; and then do what you have to do.", "Epictetus", "Discourses"],
  ["How long are you going to wait before you demand the best for yourself?", "Epictetus", "Enchiridion"],
  ["Men are disturbed not by things, but by the views which they take of things.", "Epictetus", "Enchiridion"],
  ["If you want to improve, be content to be thought foolish and stupid.", "Epictetus", "Enchiridion"],
  ["No great thing is created suddenly.", "Epictetus", "Discourses"],
  ["Only the educated are free.", "Epictetus", "Discourses"],
  ["Circumstances don't make the man, they only reveal him to himself.", "Epictetus", "Discourses"],
  ["Make the best use of what is in your power, and take the rest as it happens.", "Epictetus", "Discourses"],
  ["Wealth consists not in having great possessions, but in having few wants.", "Epictetus", ""],
  ["Well-being is attained little by little, and nevertheless is no little thing itself.", "Zeno of Citium", "via Diogenes Laërtius"],
  ["We have two ears and one mouth, so we should listen more than we say.", "Zeno of Citium", "via Diogenes Laërtius"],

  // --- Ancient Greece & Rome ---
  ["The unexamined life is not worth living.", "Socrates", "Plato's Apology"],
  ["The first and best victory is to conquer self.", "Plato", "Laws"],
  ["The beginning is the most important part of the work.", "Plato", "The Republic"],
  ["Well begun is half done.", "Aristotle", "Politics"],
  ["For the things we have to learn before we can do them, we learn by doing them.", "Aristotle", "Nicomachean Ethics"],
  ["We become brave by doing brave acts.", "Aristotle", "Nicomachean Ethics"],
  ["Happiness depends upon ourselves.", "Aristotle", "Nicomachean Ethics"],
  ["The roots of education are bitter, but the fruit is sweet.", "Aristotle", "via Diogenes Laërtius"],
  ["I count him braver who overcomes his desires than him who conquers his enemies.", "Aristotle", "via Stobaeus"],
  ["We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Will Durant", "on Aristotle, The Story of Philosophy"],
  ["Know thyself.", "Inscription at Delphi", "Temple of Apollo"],
  ["Nothing in excess.", "Inscription at Delphi", "Temple of Apollo"],
  ["No man ever steps in the same river twice.", "Heraclitus", ""],
  ["Character is destiny.", "Heraclitus", ""],
  ["The sun is new each day.", "Heraclitus", ""],
  ["Heaven never helps the man who will not act.", "Sophocles", ""],
  ["He who has begun has half done. Dare to be wise; begin!", "Horace", "Epistles"],
  ["Rule your mind, or it will rule you.", "Horace", "Epistles"],
  ["Seize the day, trusting as little as possible in tomorrow.", "Horace", "Odes"],
  ["They can because they think they can.", "Virgil", "Aeneid"],
  ["Fortune favours the bold.", "Virgil", "Aeneid"],
  ["Dripping water hollows out stone, not through force but through persistence.", "Ovid", "Epistulae ex Ponto"],
  ["Be patient and tough; someday this pain will be useful to you.", "Ovid", "Amores"],
  ["Any man can make a mistake; only a fool persists in his error.", "Cicero", "Philippics"],
  ["Practice is the best of all instructors.", "Publilius Syrus", "Sententiae"],
  ["It is a bad plan that admits of no modification.", "Publilius Syrus", "Sententiae"],
  ["Little by little does the trick.", "Aesop", "The Crow and the Pitcher"],
  ["Slow and steady wins the race.", "Aesop", "The Tortoise and the Hare"],

  // --- Eastern wisdom ---
  ["The journey of a thousand miles begins with a single step.", "Lao Tzu", "Tao Te Ching"],
  ["Mastering others is strength. Mastering yourself is true power.", "Lao Tzu", "Tao Te Ching"],
  ["He who knows others is wise; he who knows himself is enlightened.", "Lao Tzu", "Tao Te Ching"],
  ["Do the difficult things while they are easy and do the great things while they are small.", "Lao Tzu", "Tao Te Ching"],
  ["A tree as great as a man's embrace springs from a small shoot.", "Lao Tzu", "Tao Te Ching"],
  ["Nature does not hurry, yet everything is accomplished.", "Lao Tzu", ""],
  ["Learning without thought is labour lost; thought without learning is perilous.", "Confucius", "Analects"],
  ["To see what is right and not do it is want of courage.", "Confucius", "Analects"],
  ["The superior man is modest in his speech, but exceeds in his actions.", "Confucius", "Analects"],
  ["When you know a thing, to hold that you know it; and when you do not, to allow that you do not — this is knowledge.", "Confucius", "Analects"],
  ["Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.", "Sun Tzu", "The Art of War"],
  ["In the midst of chaos, there is also opportunity.", "Sun Tzu", "The Art of War"],
  ["Though one may conquer a thousand times a thousand men in battle, he is the noblest victor who conquers himself.", "The Buddha", "Dhammapada"],
  ["Drop by drop is the water pot filled.", "The Buddha", "Dhammapada"],
  ["As rain breaks through an ill-thatched house, so passion breaks through an unreflecting mind.", "The Buddha", "Dhammapada"],
  ["Better than a thousand hollow words is one word that brings peace.", "The Buddha", "Dhammapada"],
  ["You have a right to your actions, but never to your actions' fruits.", "Bhagavad Gita", "2.47"],
  ["Today is victory over yourself of yesterday; tomorrow is your victory over lesser men.", "Miyamoto Musashi", "The Book of Five Rings"],
  ["Do nothing which is of no use.", "Miyamoto Musashi", "The Book of Five Rings"],
  ["Fall seven times, stand up eight.", "Japanese proverb", ""],
  ["Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.", "Zen proverb", ""],
  ["You can't cross the sea merely by standing and staring at the water.", "Rabindranath Tagore", ""],
  ["Work is love made visible.", "Kahlil Gibran", "The Prophet"],

  // --- Scripture & proverbs ---
  ["Whatsoever thy hand findeth to do, do it with thy might.", "Ecclesiastes", "9:10"],
  ["Go to the ant, thou sluggard; consider her ways, and be wise.", "Proverbs", "6:6"],

  // --- Modern philosophy ---
  ["He who has a why to live can bear almost any how.", "Friedrich Nietzsche", "Twilight of the Idols"],
  ["What does not kill me makes me stronger.", "Friedrich Nietzsche", "Twilight of the Idols"],
  ["One must still have chaos in oneself to be able to give birth to a dancing star.", "Friedrich Nietzsche", "Thus Spoke Zarathustra"],
  ["He who would learn to fly one day must first learn to stand and walk and run and climb and dance; one cannot fly into flying.", "Friedrich Nietzsche", "Thus Spoke Zarathustra"],
  ["No one can build you the bridge on which you, and only you, must cross the river of life.", "Friedrich Nietzsche", "Schopenhauer as Educator"],
  ["Life can only be understood backwards; but it must be lived forwards.", "Søren Kierkegaard", "Journals"],
  ["To dare is to lose one's footing momentarily. Not to dare is to lose oneself.", "Søren Kierkegaard", ""],
  ["Talent hits a target no one else can hit; genius hits a target no one else can see.", "Arthur Schopenhauer", ""],
  ["Man is nothing else but what he makes of himself.", "Jean-Paul Sartre", "Existentialism Is a Humanism"],
  ["One must imagine Sisyphus happy.", "Albert Camus", "The Myth of Sisyphus"],
  ["In the depth of winter, I finally learned that within me there lay an invincible summer.", "Albert Camus", "Return to Tipasa"],
  ["It is not enough to have a good mind; the main thing is to use it well.", "René Descartes", "Discourse on the Method"],
  ["All of humanity's problems stem from man's inability to sit quietly in a room alone.", "Blaise Pascal", "Pensées"],
  ["All things excellent are as difficult as they are rare.", "Baruch Spinoza", "Ethics"],
  ["Have courage to use your own understanding.", "Immanuel Kant", "What Is Enlightenment?"],
  ["Work keeps at bay three great evils: boredom, vice, and need.", "Voltaire", "Candide"],
  ["The best is the enemy of the good.", "Voltaire", ""],
  ["My life has been full of terrible misfortunes, most of which never happened.", "Michel de Montaigne", ""],
  ["Everything can be taken from a man but one thing: the last of the human freedoms — to choose one's attitude in any given set of circumstances.", "Viktor Frankl", "Man's Search for Meaning"],
  ["Act as if what you do makes a difference. It does.", "William James", ""],
  ["Nothing is so fatiguing as the eternal hanging on of an uncompleted task.", "William James", ""],
  ["Experience is not what happens to a man; it is what a man does with what happens to him.", "Aldous Huxley", ""],
  ["Change your life today. Don't gamble on the future, act now, without delay.", "Simone de Beauvoir", ""],

  // --- Writers & poets ---
  ["Knowing is not enough; we must apply. Willing is not enough; we must do.", "Johann Wolfgang von Goethe", ""],
  ["Nothing is worth more than this day.", "Johann Wolfgang von Goethe", ""],
  ["Talent is formed in stillness, character in the world's torrent.", "Johann Wolfgang von Goethe", "Torquato Tasso"],
  ["Our doubts are traitors, and make us lose the good we oft might win by fearing to attempt.", "William Shakespeare", "Measure for Measure"],
  ["We know what we are, but know not what we may be.", "William Shakespeare", "Hamlet"],
  ["Finish each day and be done with it.", "Ralph Waldo Emerson", ""],
  ["The reward of a thing well done is to have done it.", "Ralph Waldo Emerson", "New England Reformers"],
  ["Trust thyself: every heart vibrates to that iron string.", "Ralph Waldo Emerson", "Self-Reliance"],
  ["Nothing great was ever achieved without enthusiasm.", "Ralph Waldo Emerson", "Circles"],
  ["Write it on your heart that every day is the best day in the year.", "Ralph Waldo Emerson", ""],
  ["If one advances confidently in the direction of his dreams, he will meet with a success unexpected in common hours.", "Henry David Thoreau", "Walden"],
  ["Our life is frittered away by detail. Simplify, simplify.", "Henry David Thoreau", "Walden"],
  ["It is not enough to be busy. The question is: what are we busy about?", "Henry David Thoreau", ""],
  ["Things do not change; we change.", "Henry David Thoreau", "Walden"],
  ["The chains of habit are too weak to be felt until they are too strong to be broken.", "Samuel Johnson", ""],
  ["Blessed is he who has found his work; let him ask no other blessedness.", "Thomas Carlyle", "Past and Present"],
  ["Diligence is the mother of good fortune.", "Miguel de Cervantes", "Don Quixote"],
  ["The road is always better than the inn.", "Miguel de Cervantes", ""],
  ["The mystery of human existence lies not in just staying alive, but in finding something to live for.", "Fyodor Dostoevsky", "The Brothers Karamazov"],
  ["Taking a new step, uttering a new word, is what people fear most.", "Fyodor Dostoevsky", "Crime and Punishment"],
  ["The two most powerful warriors are patience and time.", "Leo Tolstoy", "War and Peace"],
  ["Everyone thinks of changing the world, but no one thinks of changing himself.", "Leo Tolstoy", ""],
  ["Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.", "Samuel Beckett", "Worstward Ho"],
  ["Live the questions now.", "Rainer Maria Rilke", "Letters to a Young Poet"],
  ["How we spend our days is, of course, how we spend our lives.", "Annie Dillard", "The Writing Life"],
  ["Tell me, what is it you plan to do with your one wild and precious life?", "Mary Oliver", "The Summer Day"],
  ["Life shrinks or expands in proportion to one's courage.", "Anaïs Nin", ""],
  ["All we have to decide is what to do with the time that is given us.", "J. R. R. Tolkien", "The Fellowship of the Ring"],
  ["I'm not afraid of storms, for I'm learning how to sail my ship.", "Louisa May Alcott", "Little Women"],
  ["Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", "Stephen King", "On Writing"],
  ["Nothing will work unless you do.", "Maya Angelou", ""],
  ["Life is either a daring adventure or nothing.", "Helen Keller", "Let Us Have Faith"],

  // --- Science & invention ---
  ["If I have seen further it is by standing on the shoulders of giants.", "Isaac Newton", "Letter to Robert Hooke"],
  ["Life is like riding a bicycle. To keep your balance you must keep moving.", "Albert Einstein", "Letter to his son"],
  ["Imagination is more important than knowledge.", "Albert Einstein", ""],
  ["Nothing in life is to be feared, it is only to be understood.", "Marie Curie", ""],
  ["One never notices what has been done; one can only see what remains to be done.", "Marie Curie", "Letter"],
  ["A man who dares to waste one hour of time has not discovered the value of life.", "Charles Darwin", "Letter"],
  ["The first principle is that you must not fool yourself — and you are the easiest person to fool.", "Richard Feynman", ""],
  ["Genius is one percent inspiration and ninety-nine percent perspiration.", "Thomas Edison", ""],
  ["There is no substitute for hard work.", "Thomas Edison", ""],
  ["Iron rusts from disuse; stagnant water loses its purity; even so does inaction sap the vigour of the mind.", "Leonardo da Vinci", "Notebooks"],
  ["If people knew how hard I worked to get my mastery, it wouldn't seem so wonderful at all.", "Michelangelo", ""],
  ["Great things are not done by impulse, but by a series of small things brought together.", "Vincent van Gogh", "Letter to Theo"],

  // --- Statesmen & leaders ---
  ["Lost time is never found again.", "Benjamin Franklin", "Poor Richard's Almanack"],
  ["Dost thou love life? Then do not squander time, for that's the stuff life is made of.", "Benjamin Franklin", "Poor Richard's Almanack"],
  ["Energy and persistence conquer all things.", "Benjamin Franklin", ""],
  ["Well done is better than well said.", "Benjamin Franklin", "Poor Richard's Almanack"],
  ["Diligence is the mother of good luck.", "Benjamin Franklin", "Poor Richard's Almanack"],
  ["One today is worth two tomorrows.", "Benjamin Franklin", "Poor Richard's Almanack"],
  ["Little strokes fell great oaks.", "Benjamin Franklin", "Poor Richard's Almanack"],
  ["Early to bed and early to rise makes a man healthy, wealthy, and wise.", "Benjamin Franklin", "Poor Richard's Almanack"],
  ["Far and away the best prize that life offers is the chance to work hard at work worth doing.", "Theodore Roosevelt", ""],
  ["Nothing in the world is worth having or worth doing unless it means effort, pain, difficulty.", "Theodore Roosevelt", ""],
  ["Never give in, never give in, never, never, never, never.", "Winston Churchill", "Harrow School, 1941"],
  ["To improve is to change; to be perfect is to change often.", "Winston Churchill", ""],
  ["What is important is seldom urgent and what is urgent is seldom important.", "Dwight D. Eisenhower", ""],
  ["Plans are worthless, but planning is everything.", "Dwight D. Eisenhower", ""],
  ["If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", "Martin Luther King Jr.", ""],
  ["Faith is taking the first step even when you don't see the whole staircase.", "Martin Luther King Jr.", ""],
  ["If there is no struggle, there is no progress.", "Frederick Douglass", ""],
  ["Success is to be measured not so much by the position one has reached in life as by the obstacles which he has overcome.", "Booker T. Washington", "Up from Slavery"],
  ["You must do the thing you think you cannot do.", "Eleanor Roosevelt", "You Learn by Living"],
  ["I attribute my success to this — I never gave or took any excuse.", "Florence Nightingale", ""],
  ["The most effective way to do it, is to do it.", "Amelia Earhart", ""],

  // --- Work, focus & performance ---
  ["There is nothing so useless as doing efficiently that which should not be done at all.", "Peter Drucker", ""],
  ["You do not rise to the level of your goals. You fall to the level of your systems.", "James Clear", "Atomic Habits"],
  ["Every action you take is a vote for the type of person you wish to become.", "James Clear", "Atomic Habits"],
  ["Clarity about what matters provides clarity about what does not.", "Cal Newport", "Deep Work"],
  ["Discipline equals freedom.", "Jocko Willink", ""],
  ["Discipline is the bridge between goals and accomplishment.", "Jim Rohn", ""],
  ["Either you run the day or the day runs you.", "Jim Rohn", ""],
  ["You will never change your life until you change something you do daily.", "John C. Maxwell", ""],
  ["The only way to do great work is to love what you do.", "Steve Jobs", "Stanford commencement, 2005"],
  ["I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.", "Bruce Lee", ""],
  ["Absorb what is useful, discard what is useless, add what is specifically your own.", "Bruce Lee", ""],
  ["Don't quit. Suffer now and live the rest of your life as a champion.", "Muhammad Ali", ""],
  ["Champions aren't made in gyms. Champions are made from something they have deep inside them — a desire, a dream, a vision.", "Muhammad Ali", ""],
  ["I've failed over and over and over again in my life. And that is why I succeed.", "Michael Jordan", ""],
];
